export const mockEvents = [
  {
    eventId: 1,
    title: "Lễ hội Nghinh Ông",
    image: "https://baotangphunu.com/wp-content/uploads/2022/06/R637127776440606368-scaled.jpg",
    content: "Lễ hội truyền thống tôn vinh cá Ông, cầu nguyện cho ngư dân an toàn.",
    eventType: "Lễ hội văn hóa",
    status: "Đang diễn ra",
    createdDate: "2024-03-01",
    createdBy: "Ban Tổ chức Lễ hội",
    startDate: "15",
    endDate: "17 tháng 5, 2024",
    provinceName: "Bà Rịa - Vũng Tàu",
    address: "Đền thờ Cá Ông, Thành phố Vũng Tàu",
    description: "Lễ hội Nghinh Ông là một trong những lễ hội truyền thống lớn nhất tại Vũng Tàu, thu hút hàng nghìn người tham gia mỗi năm."
  },
  {
    eventId: 2,
    title: "Hội chợ Du lịch Biển",
    image: "https://media-cdn-v2.laodong.vn/storage/newsportal/2024/4/29/1333886/Bien-Vung-Tau.jpg",
    content: "Hội chợ giới thiệu các sản phẩm du lịch biển đặc sắc của Vũng Tàu.",
    eventType: "Hội chợ",
    status: "Sắp đến",
    createdDate: "2024-03-10",
    createdBy: "Sở Du lịch Bà Rịa - Vũng Tàu",
    startDate: "01",
    endDate: "05 tháng 6, 2024",
    provinceName: "Bà Rịa - Vũng Tàu",
    address: "Công viên Bãi Trước, Thành phố Vũng Tàu",
    description: "Hội chợ Du lịch Biển là cơ hội tuyệt vời để khám phá các điểm đến và dịch vụ du lịch hấp dẫn của Vũng Tàu."
  },
  {
    eventId: 3,
    title: "Giải đua thuyền buồm quốc tế",
    image: "https://thoidai.com.vn/stores/news_dataimages/thoidai/022019/15/10/hap-dan-giai-dua-thuyen-buom-tranh-cup-vung-tau-marina-12-.1488.jpg",
    content: "Cuộc thi đua thuyền buồm với sự tham gia của các đội tuyển quốc tế.",
    eventType: "Thể thao",
    status: "Sắp đến",
    createdDate: "2024-03-15",
    createdBy: "Liên đoàn Thể thao Dưới nước Việt Nam",
    startDate: "10",
    endDate: "15 tháng 7, 2024",
    provinceName: "Bà Rịa - Vũng Tàu",
    address: "Bãi Sau, Thành phố Vũng Tàu",
    description: "Giải đua thuyền buồm quốc tế là sự kiện thể thao biển đẳng cấp, thu hút các vận động viên hàng đầu từ nhiều quốc gia."
  },
  {
    eventId: 4,
    title: "Lễ hội Ẩm thực Đường phố",
    image: "https://media-cdn-v2.laodong.vn/storage/newsportal/2023/11/18/1269129/Cho-Ngoi.jpg",
    content: "Lễ hội giới thiệu các món ăn đường phố đặc trưng của Vũng Tàu.",
    eventType: "Ẩm thực",
    status: "Đang diễn ra",
    createdDate: "2024-04-01",
    createdBy: "Hiệp hội Du lịch Bà Rịa - Vũng Tàu",
    startDate: "20",
    endDate: "25 tháng 4, 2024",
    provinceName: "Bà Rịa - Vũng Tàu",
    address: "Đường Thùy Vân, Thành phố Vũng Tàu",
    description: "Lễ hội Ẩm thực Đường phố là dịp để thưởng thức các món ăn ngon và đặc sản của Vũng Tàu trong không khí sôi động."
  },
  {
    eventId: 5,
    title: "Triển lãm Nghệ thuật Biển",
    image: "https://ittpa.baria-vungtau.gov.vn/portal/editor/images/festival.jpg",
    content: "Triển lãm trưng bày các tác phẩm nghệ thuật lấy cảm hứng từ biển.",
    eventType: "Nghệ thuật",
    status: "Sắp đến",
    createdDate: "2024-04-15",
    createdBy: "Hội Mỹ thuật Bà Rịa - Vũng Tàu",
    startDate: "01",
    endDate: "10 tháng 8 ,2024",
    provinceName: "Bà Rịa - Vũng Tàu",
    address: "Bảo tàng Bà Rịa - Vũng Tàu",
    description: "Triển lãm Nghệ thuật Biển quy tụ các tác phẩm độc đáo từ nhiều nghệ sĩ, thể hiện vẻ đẹp và sức sống của biển cả."
  },
  {
    eventId: 6,
    title: "Festival Diều Vũng Tàu",
    image: "https://vntravel.org.vn/uploads/images/2024/03/16/419257093-754920120074997-7158977836238136303-n-1710564765.jpg",
    content: "Lễ hội thả diều với sự tham gia của các nghệ nhân trong và ngoài nước.",
    eventType: "Văn hóa",
    status: "Sắp đến",
    createdDate: "2024-05-01",
    createdBy: "Trung tâm Văn hóa Thông tin và Thể thao Vũng Tàu",
    startDate: "05",
    endDate: "07 tháng 9, 2024",
    provinceName: "Bà Rịa - Vũng Tàu",
    address: "Bãi biển Bãi Sau, Thành phố Vũng Tàu",
    description: "Festival Diều Vũng Tàu là sự kiện văn hóa độc đáo, nơi bầu trời Vũng Tàu được tô điểm bởi hàng trăm cánh diều đủ màu sắc và hình dáng."
  }
];